#include "Class A.h"




void Class A::perimeter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-12-25f6c9a1:16f10d9d991:-8000:0000000000000870 begin
{
}
// section -64--88-1-12-25f6c9a1:16f10d9d991:-8000:0000000000000870 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class A::aire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-12-25f6c9a1:16f10d9d991:-8000:0000000000000874 begin
{
}
// section -64--88-1-12-25f6c9a1:16f10d9d991:-8000:0000000000000874 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
